--sqlfluff:dialect:teradata

REPLACE VIEW DEVV_STG_FLX.[tableNme]_GET_DELTA AS
LOCK ROW FOR ACCESS

SELECT
COALESCE(X.[PK], Y.[PK]) AS [PK],
X.[NON_PK_COL],
-------NO_CHANGE-----------
COALESCE(X.ETL_START_DT,Y.ETL_START_DT) AS ETL_START_DT,
X.ETL_END_DT,
X.RECORD_DELETED_FLAG,
X.PROCESS_NAME,
X.UPDATE_PROCESS_NAME,
X.EXT_SS_ID,
X.EXE_PROCESS_ID,
X.UPDATE_PROCESS_ID,
COALESCE(X.ETL_START_TS,Y.ETL_START_TS) AS ETL_START_TS,
X.ETL_END_TS,
CASE WHEN Y.[PK]  IS NULL THEN 'INS' --- IF MULTIPLE PKs are there then concatenate them with AND
WHEN X.[PK] = Y.[PK]  --- IF MULTIPLE PKs are there then concatenate them with AND
AND(
((X.[NON_PK_COL] IS NULL AND [Y.NON_PK_COL] IS NOT NULL) OR ([X.NON_PK_COL] IS NOT NULL AND [Y.NON_PK_COL] IS NULL) OR ([X.NON_PK_COL] <> [Y.NON_PK_COL])) OR
) THEN 'UPD'
WHEN X.[PK] IS NULL THEN 'DEL' --- IF MULTIPLE PKs are there then concatenate them with AND
END AS OPT_FLAG
FROM DEVT_STG_FLX.[ tableNme] X
FULL JOIN DEVT_STG_FLX.[ tableNme]_BACKUP Y
ON X.[PK] = Y.[PK] --- IF MULTIPLE PKs are there then concatenate them with AND
WHERE OPT_FLAG IS NOT NULL;
